### ISSUE TITLE
[Bug]: Can't install with Laravel 11

### ISSUE THREAD

**Issue by agencetwogether** [visualbuilder/user-consent#4]
### What happened?

Hello,

With Laravel 11, error with require package, 
Conflict with illuminate/contracts.

Please update accordingly

Thanks

### How to reproduce the bug

composer require visualbuilder/user-consent 

=> 
```
Problem 1
    - Root composer.json requires visualbuilder/user-consent * -> satisfiable by visualbuilder/user-consent[3.0.1, ..., 3.0.16].
    - visualbuilder/user-consent[3.0.1, ..., 3.0.16] require illuminate/contracts ^10.0 -> found illuminate/contracts[v10.0.0, ..., v10.48.20] but these were not loaded, likely because it conflicts with another require.
```

### Package Version

3.2.100

### PHP Version

8.2

### Laravel Version

11.22.0

**Comment by cannycookie** [comment]
Hi, thanks for reporting this.  I've updated composer to use illuminate 11. Must admit it's not tested with 11 but  it's on the todo list.

**Comment by agencetwogether** [comment]
Ok package is still developing ? Because I have many error after install it ?#Le 8 sept. 2024 à 21:23, Lee ***@***.***> a écrit :﻿
Hi, thanks for reporting this.  I've updated composer to use illuminate 11. Must admit it's not tested with 11 but  it's on the todo list.

**Comment by cannycookie** [comment]
Ah OK. Sorry seems like not ready for L11 yet.  I'll let you know when we've updated it.
